#include <string.h>
#include "esp_err.h"
#include "esp_log.h"
#include "driver/gpio.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "sdkconfig.h" // generated by "make menuconfig"
#include "sh1106.h"
#include "rc522.h"


const int SDA_PIN=GPIO_NUM_21;
const int SCL_PIN=GPIO_NUM_22;

static const char* TAG = "RFID";

void tag_handler(uint8_t* sn) { // serial number is always 5 bytes long
    task_sh1106_display_clear(NULL);
    ESP_LOGI(TAG, "Tag: %#x %#x %#x %#x %#x",
        sn[0], sn[1], sn[2], sn[3], sn[4]
    );
    task_sh1106_display_text(sn);
}

void app_main(void)
{
    const rc522_start_args_t start_args = {
        .miso_io  = 19,
        .mosi_io  = 23,
        .sck_io   = 18,
        .sda_io   = 5,
        .callback = &tag_handler,
    };
    rc522_start(start_args);

	sh1106_init(SDA_PIN, SCL_PIN);
	task_sh1106_display_pattern(NULL);
	vTaskDelay(1000/portTICK_PERIOD_MS);
	task_sh1106_display_clear(NULL);
    task_sh1106_display_text("Hello!\nMultiline OK!\nAnother line.");
}